#!/bin/bash
#
# recreate + restart  (без удаления БД! данные остаются в volums mysql-hdd)
docker-compose stop;

cd logs && rm -f *.log && cd ..

docker-compose up -d;
./fix-permitions.sh
sleep 1;

docker-compose ps;

sleep 2;

docker-compose ps

